### ISSUE TITLE
RTMP streaming. Audio isn't played

### ISSUE THREAD

**Issue by IlyaMyasoedov** [mrmaffen/vlc-android-sdk#10]
I am developing the android app that streams the audio and uses RTMP. I added libvlc .aar file to my project but the audio isn't played. (My server is Wowza). The link example "rtmp://178.132.203.158:1935/music/_definst_/mp3:a33/yb5/gsa/a33yb5gsa370.mp3?wowzartmpstart=1792&wowzartmpduration=20000"

**Comment by mrmaffen** [comment]
I merely publish the libvlc android sdk on maven. Please ask the videolan dev team directly.
