### ISSUE TITLE
When you compile the vlc, what's your GnuTLS  version?

### ISSUE THREAD

**Issue by hon0225** [mrmaffen/vlc-android-sdk#11]
Hi dear, I want to know when your compile the vlc, which the gnutls version in use ?The vulnerability was addressed in GnuTLS 3.1.25, GnuTLS 3.2.15 and GnuTLS 3.3.4
thx!

**Comment by mrmaffen** [comment]
Hi darling,
the package version I'm using is 2.12.23-12ubuntu2
