### ISSUE TITLE
arm64-v8a support

### ISSUE THREAD

**Issue by FabianTerhorst** [mrmaffen/vlc-android-sdk#12]
Hello,

when i try the sdk with my nexus 6p i get following error:

Can't load vlcjni library: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/packagename/base.apk"],nativeLibraryDirectories=[/data/app/packagename-1/lib/arm64, /data/app/packagename-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libvlcjni.so"

**Comment by FabianTerhorst** [comment]
Here is the commit from vlc to add arm64 v8a support: https://mailman.videolan.org/pipermail/android/2014-October/004633.html

**Comment by mrmaffen** [comment]
Your Nexus 6p should run armv7a apps just fine.

**Comment by FabianTerhorst** [comment]
I fixed it by building the v8a from source

**Comment by lisnstatic** [comment]
hello,I hava met a  question，after  the  video paused a  little  long  time，then  start  the video，there is  only  the  sound  and  the surfaceview  do not move  any  more.
thanks  inadvance~

**Comment by mrmaffen** [comment]
https://github.com/mrmaffen/vlc-android-sdk/commit/07ca81bf9b9c3ac4d529d698d23e232fd6515d24
