### ISSUE TITLE
OpenSLES OutputMix interface 0 not available

### ISSUE THREAD

**Issue by zishanj** [mrmaffen/vlc-android-sdk#13]
I am using your built SDK for android application. Unfortunately I am receiving this error while running `MediaPlayer.play()`:

    W/libOpenSLES(23077): class OutputMix interface 0 requested but unavailable MPH=43

The audio doesn't play at all and there is also now volume. Is there any workaround to this please?

**Comment by mrmaffen** [comment]
Please contact the videolan dev team directly. I merely publish the SDK.
