### ISSUE TITLE
Use of this library.

### ISSUE THREAD

**Issue by deepakvvdn** [mrmaffen/vlc-android-sdk#18]
How to use this library. Im using an older one when i try to include this current version its giving me error. Please give me sample code link. I am using 1.0.3

Thanks.

**Comment by nthreads** [comment]
This is how I achieved streaming using latest version of this lib.

package com.a2l.vlc;

import android.content.res.Configuration;
import android.net.Uri;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.view.Gravity;
import android.view.SurfaceHolder;
import android.view.SurfaceView;
import android.view.ViewGroup;
import android.view.WindowManager;
import android.widget.MediaController;
import android.widget.Toast;

import org.videolan.libvlc.IVLCVout;
import org.videolan.libvlc.LibVLC;
import org.videolan.libvlc.Media;
import org.videolan.libvlc.MediaPlayer;
import org.videolan.libvlc.media.VideoView;

import java.lang.ref.WeakReference;
import java.util.ArrayList;

/**
 * Package Name : com.a2l.vlc
 * Created by Muhammad Nauman Zubair on 2/2/2016 12:48 PM
 */
public class StreamingActivity extends AppCompatActivity implements IVLCVout.Callback, LibVLC.HardwareAccelerationError {
    private static final String TAG = StreamingActivity.class.getSimpleName();

    private String mVideoUrl;

    // media player
    private LibVLC libvlc;
    private VideoView videoView;

    private MediaPlayer mMediaPlayer = null;
    private int mVideoWidth;
    private int mVideoHeight;
    private final static int VideoSizeChanged = -1;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        this.getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
        this.getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);

        setContentView(R.layout.activity_streaming);

        videoView = (VideoView) findViewById(R.id.video_view);
        mVideoUrl = getIntent().getExtras().getString("videoUrl");
    }

    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        setSize(mVideoWidth, mVideoHeight);
    }

    @Override
    protected void onResume() {
        super.onResume();
        //createPlayer(mVideoUrl);
        createMediaPlayer();
    }

    @Override
    protected void onPause() {
        super.onPause();
        releasePlayer();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        releasePlayer();
    }

    /*************
     * Surface
     *************/
    private void setSize(int width, int height) {
        mVideoWidth = width;
        mVideoHeight = height;
        if (mVideoWidth * mVideoHeight <= 1)
            return;

        if(videoView == null || videoView == null)
            return;

        // get screen size
        int w = getWindow().getDecorView().getWidth();
        int h = getWindow().getDecorView().getHeight();

        // getWindow().getDecorView() doesn't always take orientation into
        // account, we have to correct the values
        boolean isPortrait = getResources().getConfiguration().orientation == Configuration.ORIENTATION_PORTRAIT;
        if (w > h && isPortrait || w < h && !isPortrait) {
            int i = w;
            w = h;
            h = i;
        }

        float videoAR = (float) mVideoWidth / (float) mVideoHeight;
        float screenAR = (float) w / (float) h;

        if (screenAR < videoAR)
            h = (int) (w / videoAR);
        else
            w = (int) (h * videoAR);

        // force surface buffer size
        videoView.getHolder().setFixedSize(mVideoWidth, mVideoHeight);

        // set display size
        ViewGroup.LayoutParams lp = videoView.getLayoutParams();
        lp.width = w;
        lp.height = h;
        videoView.setLayoutParams(lp);
        videoView.invalidate();
    }


    private void createMediaPlayer() {
        releasePlayer();

        try {
            if (mVideoUrl.length() > 0) {
                Toast toast = Toast.makeText(this, mVideoUrl, Toast.LENGTH_LONG);
                toast.setGravity(Gravity.BOTTOM | Gravity.CENTER_HORIZONTAL, 0,
                        0);
                toast.show();
            }

            // Create LibVLC
            ArrayList<String> options = new ArrayList<String>();
            //options.add("--subsdec-encoding <encoding>");
            options.add("--aout=opensles");
            options.add("--audio-time-stretch"); // time stretching
            options.add("-vvv"); // verbosity
            libvlc = new LibVLC(options);
            libvlc.setOnHardwareAccelerationError(this);


            mMediaPlayer = new MediaPlayer(libvlc);
            mMediaPlayer.setEventListener(mPlayerListener);

//            final IVLCVout vout = mMediaPlayer.getVLCVout();
//            vout.setVideoView(videoView);
//            vout.addCallback(this);
//            vout.attachViews();

            videoView.setVideoPath(mVideoUrl);
            videoView.setVideoURI(Uri.parse(mVideoUrl));
            videoView.setMediaController(new MediaController(this));
            videoView.setOnPreparedListener(new android.media.MediaPlayer.OnPreparedListener() {
                @Override
                public void onPrepared(android.media.MediaPlayer mp) {
                    Log.d("TAG", "OnPrepared called");
                }
            });

            videoView.start();

        } catch (Exception e) {
            e.printStackTrace();
            Toast.makeText(this, "Error creating player!", Toast.LENGTH_LONG).show();
        }
    }
    
    // TODO: handle this cleaner
    private void releasePlayer() {
        if (libvlc == null)
            return;
        mMediaPlayer.stop();
        final IVLCVout vout = mMediaPlayer.getVLCVout();
        vout.removeCallback(this);
        vout.detachViews();
        videoView = null;
        libvlc.release();
        libvlc = null;

        mVideoWidth = 0;
        mVideoHeight = 0;
    }

    /*************
     * Events
     *************/

    private MediaPlayer.EventListener mPlayerListener = new MyPlayerListener(this);

    @Override
    public void onNewLayout(IVLCVout vout, int width, int height, int visibleWidth, int visibleHeight, int sarNum, int sarDen) {
        if (width * height == 0)
            return;

        // store video size
        mVideoWidth = width;
        mVideoHeight = height;
        setSize(mVideoWidth, mVideoHeight);
    }

    @Override
    public void onSurfacesCreated(IVLCVout vout) {

    }

    @Override
    public void onSurfacesDestroyed(IVLCVout vout) {

    }

    private static class MyPlayerListener implements MediaPlayer.EventListener {
        private WeakReference<StreamingActivity> mOwner;

        public MyPlayerListener(StreamingActivity owner) {
            mOwner = new WeakReference<StreamingActivity>(owner);
        }

        @Override
        public void onEvent(MediaPlayer.Event event) {
            StreamingActivity player = mOwner.get();

            switch(event.type) {
                case MediaPlayer.Event.EndReached:
                    Log.d(TAG, "MediaPlayerEndReached");
                    player.releasePlayer();
                    break;
                case MediaPlayer.Event.Playing:
                case MediaPlayer.Event.Paused:
                case MediaPlayer.Event.Stopped:
                default:
                    break;
            }
        }
    }

    @Override
    public void eventHardwareAccelerationError() {
        // Handle errors with hardware acceleration
        Log.e(TAG, "Error with hardware acceleration");
        this.releasePlayer();
        Toast.makeText(this, "Error with hardware acceleration", Toast.LENGTH_LONG).show();
    }
}

**Comment by deepakvvdn** [comment]
Thanks dude. have you any link for this code?

**Comment by nthreads** [comment]
No, I don't have code link.

**Comment by deepakvvdn** [comment]
I am using like this but LibVlc.restart(mActivity) , here application is getting crashed? why? Can you help me on this?
public void createPlayer(String mediaPathToPlay) {
        releasePlayer();
        try {
            // Create a new media player
            libvlc = LibVLC.getInstance();
            if (libvlc != null) {
                libvlc.setHardwareAcceleration(LibVLC.HW_ACCELERATION_DISABLED);
                libvlc.setFrameSkip(true);
                libvlc.setNetworkCaching(300);
                libvlc.setSubtitlesEncoding("");
                libvlc.setAout(LibVLC.AOUT_OPENSLES);
                libvlc.setTimeStretching(true);
                libvlc.setChroma("RV32");
                libvlc.setVerboseMode(false);
//                LibVLC.restart(mActivity);
                EventHandler.getInstance().addHandler(mHandler);
                if (holder != null) {
                    holder.setFormat(PixelFormat.RGBX_8888);
                    holder.setKeepScreenOn(true);
                } else {
                    Utils.showLog(TAG, "holder is null");
                    holder = mSurface.getHolder();
                    holder.setFormat(PixelFormat.RGBX_8888);
                    holder.setKeepScreenOn(true);

                }
                Utils.showLog(TAG, "Path to play : " + mediaPathToPlay);
                MediaList list = libvlc.getMediaList();
                list.clear();
                list.add(new Media(libvlc, LibVLC.PathToURI(mediaPathToPlay)), false);
//                libvlc.playIndex(0);
            } else {
                Utils.showLog(TAG, "libVlv is null");
            }
        } catch (Exception e) {
            Utils.showLog(TAG, e + "error");
            Toast.makeText(mActivity, "Error creating player!", Toast.LENGTH_LONG).show();
        }
    }

**Comment by deepakvvdn** [comment]
Hi how to get error callbacks like:

 live555 demux: connection error 404
02-16 14:15:00.486 15058-23326/org.linphone E/VLC: live555 demux: Failed to connect with rtsp://52.24.90.251:8554/sb_26_sf13a/device_577
02-16 14:15:00.486 15058-23326/org.linphone E/VLC: live555 demux: TCP rollover failed, aborting

these are just printing from the c source native code. How I can get these errors in JAVA, to handle these kind of errors. 

Pls help. Thanks in advance.

**Comment by mrmaffen** [comment]
Please contact the videolan team directly. I am only publishing LibVLC for Android on Maven Central.

https://trac.videolan.org/vlc

**Comment by lisnstatic** [comment]
@nthreads  hello！I have use your activity，but it still can‘t  play  the video，can you give me a  demo         
 which can  run  normally。thank you very very much！my email is     lisnit@163.com

**Comment by abhijeetbhanjadeo** [comment]
Gary Anderson has a working code https://github.com/gareoke/VLCPlayer, using this library on Maven Central.

Thanks Gary for sharing it.

**Comment by deepakvvdn** [comment]
Thanks abhi, I am not playing my video using vlc, its working fine, Is anyone know how to capture snapshot using vlc? I am not able to capture the snapshot. thumbnail im getting as null, Any Idea?

**Comment by abhijeetbhanjadeo** [comment]
Not sure, if this can help https://forum.videolan.org/viewtopic.php?f=35&t=125119&p=420749&hilit=vlc_args#p420749

**Comment by deepakvvdn** [comment]
Thanks abhijeet, I will try this. Actually I was looking for the code where I can enable from java,because I am using pre-compiled vlc sdk,  but it seems like i need to update into c files.

**Comment by vkdinventor** [comment]
@lisnstatic  Please try my simple vlc player https://github.com/vkdinventor/MyVlcPlayer

**Comment by fartymonk** [comment]
Hi, anyone has a working sample using latest libvlc (3.0.0)  (de.mrmaffen:vlc-android-sdk:2.0.6) ?

I've seen the sample @abhijeetbhanjadeo gave, but it uses old version (de.mrmaffen:vlc-android-sdk:1.x.x) and when I update the dependency on that project, IVideoPlayer has been removed and also other functions and classes.

@vkdinventor thank you for the sample, I wonder though, I see you use the IVideoPlayer, where did this class came from? I used the gradle dependency only (whchi I believe supposed to add the LibVLC into my project). 

Do I also need to copy the files under your `MyVlcPlayer/app/src/main/java/org/videolan/libvlc/` to my project to be able to use this? If yes, what's different between the LibVLC added by this gradle dependency and the ones in your project folder? I'm new to Android and VLC, so please help me kindly. Thank you.

**Comment by deepakvvdn** [comment]
i can share working demo

**Comment by fartymonk** [comment]
@deepakvvdn oh, yes, please! :) And thank you so much!

**Comment by deepakvvdn** [comment]
are u on skype? send me skypeid

**Comment by deepakvvdn** [comment]
send email id

**Comment by fartymonk** [comment]
here's my email : fartymonk@gmail.com. :)

**Comment by karthickbabu** [comment]
@AndyKD Can you send the working code to this mail id too karthickbabu@yahoo.com

**Comment by AndyKD** [comment]
it costs around $5 :p hahahah

**Comment by vkdinventor** [comment]
@fartymonk  remove gradle dependency and just copy libvlc into your project as I did. Gradle dependency might be using different version thats why IVideoPlayer class is not there.

**Comment by iHad169** [comment]
@vkdinventor We need to dependency two different version libvlc?

**Comment by xperiafan13-rom** [comment]
please send me the sample mundorap2010@gmail.com

**Comment by mohammedragabmohammedborik** [comment]
this method can not apply it any help please i want video to full screen

@override
public void onNewLayout(IVLCVout vout, int width, int height, int visibleWidth, int visibleHeight, int sarNum, int sarDen) {
if (width * height == 0)
return;

// store video size
mVideoWidth = width;
mVideoHeight = height;
setSize(mVideoWidth, mVideoHeight);

}

**Comment by mohammedragabmohammedborik** [comment]
thank you can you give me xml layout

**Comment by vkdinventor** [comment]
@iHad169  No,

**Comment by Francenzo** [comment]
For anyone triyng to figure out the issue with onNewLayout @mohammedragabmohammedborik The difference is the use of AppCompatActivity. Instead of onNewLayout use the listener below then use addOnLayoutChangeListener on your surface


OnLayoutChangeListener mLayoutChangeListener = new OnLayoutChangeListener() {
	@Override
	public void onLayoutChange(View v, int left, int top, int right, int bottom, int oldLeft, int oldTop, int oldRight, int oldBottom) {
		// store video size
		mVideoWidth = right - left;
		mVideoHeight = bottom - top;
		setSize(mVideoWidth, mVideoHeight);
	}
};

**Comment by myatmon** [comment]
@AndyKD  can you sent me working code of libvlc? ms.myatmonshein@gmail.com

**Comment by vkdinventor** [comment]
@myatmon try this sample https://github.com/vkdinventor/MyVlcPlayer

**Comment by navdeepkhera04** [comment]
@AndyKD  please send libvlc working code for RTMP streaming with the reduced delay to navdeepkhera04@gmail.com
