### ISSUE TITLE
How to use? and why don't playing?

### ISSUE THREAD

**Issue by vaszol** [mrmaffen/vlc-android-sdk#19]
I installed the dependency link and wrote an example. If it use the standard class MediaPlayer, the local video playing. And if you use org.videolan.libvlc.media.MediaPlayer, it does not show any local or what the link.
Please tell me what I did wrong?

[my code](https://github.com/vaszol/StreamPlayer/tree/5597d03d8dd90352e708787dd9ee963834a6f15a)

**Comment by mrmaffen** [comment]
Please contact the videolan team directly. I am only publishing LibVLC for Android on Maven Central.

https://trac.videolan.org/vlc
