### ISSUE TITLE
Can't load vlcjni library: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by vibin** [mrmaffen/vlc-android-sdk#2]
Hey there.

I know I really should be asking this question at VLC Forums or IRC, but my IP got banned at the Forums (no idea why) and no one really helps on the IRC channel.

I compiled VLC, got the .so files and then imported it as an Existing Project into my Gradle. All this worked fine.

But problem 1: the .so files don't get copied to /data/data/<app-name>/lib/  when I run gradle build. Do I have to make any changes to build.gradle?

Problem 2: I tried manually copying libvlcjni.so to /data/data/<app-name>/lib/. But still system.loadLibrary() doesn't work.

It says

```
21221               dalvikvm  E  dlopen("/data/data/com.vibin.billy.debug/lib/libvlcjni.so") failed: dlopen failed: library "/data/data/com.vibin.billy.debug/lib/libvlcjni.so" not found
21221             VLC/LibVLC  E  Can't load vlcjni library: java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/data/com.vibin.billy.debug/lib/libvlcjni.so" not found
```

Thanks a lot!

**Comment by Uzair-Mohammad** [comment]
I am also facing the same problem, i am using 'de.mrmaffen:vlc-android-sdk:1.0.6'! please help.
