### ISSUE TITLE
Not able to get snapshot.

### ISSUE THREAD

**Issue by deepakvvdn** [mrmaffen/vlc-android-sdk#20]
Hi,

Thanks video is playing fine. But I have one more issue I am not able to capture snapshot of current frame. their is one method getThumbnail but its returning me as null.

 snapshotBytes = libvlc.getThumbnail(mediaUrl, 300, 300);

How to get this please help!!

**Comment by deepakvvdn** [comment]
Can anybody answer to this question please?

**Comment by mrmaffen** [comment]
Please contact the videolan team directly. I am only publishing LibVLC for Android on Maven Central.

https://trac.videolan.org/vlc
