### ISSUE TITLE
m3u8 live stream stop problem

### ISSUE THREAD

**Issue by Hamdy-khader** [mrmaffen/vlc-android-sdk#21]
hello there
i've implemented the library successfully, but the issue is that when i stop the stream, the application freezes and uses a 50% of the cpu and never unfreeze 
 i use mediaPlayer.stop(); in the main thread

**Comment by nthreads** [comment]
I faced similar problems, now im gonna use ExoPlayer

**Comment by Hamdy-khader** [comment]
too bad :(

**Comment by mrmaffen** [comment]
Please contact the videolan team directly. I am only publishing LibVLC for Android on Maven Central.

https://trac.videolan.org/vlc
