### ISSUE TITLE
How to use vlc-android-sdk ?

### ISSUE THREAD

**Issue by hulegithub** [mrmaffen/vlc-android-sdk#23]
Can you give some development steps for us , thank you very much

**Comment by Dakor91** [comment]
There are examples on the official Videolan server: 
https://code.videolan.org/videolan/libvlc-android-samples
and
https://code.videolan.org/videolan/vlc-android

This Git Repo is not powered by the Videolan Team.

**Comment by hulegithub** [comment]
thanks again
