### ISSUE TITLE
Handle VLC errors

### ISSUE THREAD

**Issue by Greg767** [mrmaffen/vlc-android-sdk#29]
Hi,
I know there is no VLC support here, but just in case... either its a simple thing, or someone else knows the answer.
So I am getting these errors when I try to load an URI that is not woring for some reason.
`E/VLC: [7126d274] core input: Your input can't be opened
E/VLC: [7126d274] core input: VLC is unable to open the MRL ...`
And I really would like to handle these exceptions but I cannot find a callback. The URIs are from a database so I cannot know in advance.
Thanks in advance if you know the answer and can take a little time to respond!
Greg

**Comment by rniebecker** [comment]
Hey,

make sure the scheme of the Uri is set correctly, eg. if you want to play a local file use:
Uri.fromFile(new File(path));

Without a valid scheme you won't be able to playback any video.

Hope this helps,
Ralf

**Comment by Greg767** [comment]
Hi,
Thanks a lot for the hint.
The URI scheme is correct. I am loading .ts files from a server, but a .ts file can be broken or empty and this is the case that I don't know how to handle.
I am using the version 1.9.0 and this version crashes when I try to load a working .ts file just after a failed .ts file. So I'd like to re-create the player whenever I get a broken file, but at the moment I don't know when to recreate the player. I'd like to avoid recreating at every file change.
Thanks

**Comment by rniebecker** [comment]
Hey,

Create a new Media object and call parse() or parseAsync() and assign the new Media object to the MediaPlayer using setMedia();

You might want to release your old Media object as well.

If you release the MediaPlayer it will probably release the surface as well which you might not want to do.

Cheers,
Ralf

**Comment by Greg767** [comment]
Yeah I was doing like that, but was not calling parse() on the Media object. Now that I call parseAsync() it seems that the crash is gone.
Cool thanks!!!

But for some reason you haven't answered my question :)

What if I'd like to display an error message when `core input: VLC is unable to open the MRL` arrives? Is there no way to catch this?
Thanks very much in advance.

Greg

**Comment by troy379** [comment]
Hi guys,
Do you happen to know is there any updates on this?

**Comment by ieg28** [comment]
Benim çözümüm bu şekilde logcat kullanarak oldu.

Basit bir log reader classı
```
 public static final class MyLibVLCLogReader {
        private static final String TAG = MyLibVLCLogReader.class.getCanonicalName();

        private static String[] runClearCMD = new String[]{"logcat", "-c"};
        private static String[] runCMD = new String[]{"logcat", "*:D", "-e", "libvlc"};

        private Thread thread;
        private boolean isRun = true;

        private OnLogListener logListener;

        public MyLibVLCLogReader() {
            thread = new Thread(runnable);
        }

        public MyLibVLCLogReader(OnLogListener listener) {
            logListener = listener;
            thread = new Thread(runnable);
        }

        public void Start() {
            thread.start();
        }

        public void Stop() {
            isRun = false;
        }

        private Runnable runnable = new Runnable() {
            @Override
            public void run() {
                Log.v(TAG, "Begin listening logger");
                try {
                    // Clear logs
                    Runtime.getRuntime().exec(runClearCMD);

                    // Capture logs
                    Process process = Runtime.getRuntime().exec(runCMD);
                    BufferedReader bufferedReader = new BufferedReader(
                            new InputStreamReader(process.getInputStream()));

                    String line;
                    while (isRun && (line = bufferedReader.readLine()) != null) {
                        if (logListener != null) logListener.onLogCapture(line);
                    }

                    bufferedReader.close();
                    process.destroy();
                } catch (IOException e) {
                    e.printStackTrace();
                }

                Log.v(TAG, "Exit listening logger");
            }
        };

        public interface OnLogListener {
            public void onLogCapture(String line);
        }
    }
```

Kullanırken log okuma iznine ihtiyacınız var.
```
    <uses-permission
        android:name="android.permission.READ_LOGS"
        tools:ignore="ProtectedPermissions" />
```
