### ISSUE TITLE
Upgrade to 2.0.0 in order to add support for buffering events

### ISSUE THREAD

**Issue by CRASH-Tech** [mrmaffen/vlc-android-sdk#33]
Hello, please add buffering event like this
https://code.videolan.org/videolan/vlc-android/commit/1c4b6c51cb33dc884f78e7c7bb4b9e9d8eff18fc

**Comment by rniebecker** [comment]
+1

The fix is in version 2.0.0 of the vlc-android project.

Getting finally access to the buffering event is very important for creating a good experience when using libVLC on Android.

Please release a new 2.0.0 version as soon as possible, I've been waiting for this. :)

Thanks,
Ralf

**Comment by iyrul** [comment]
Wow It will be a good news for the next update.

**Comment by sreichholf** [comment]
Until the original repo is being update you could go and use my repo https://github.com/sreichholf/vlc-android-sdk (pull request has been opened)

**Comment by kazemihabib** [comment]
+1

**Comment by KirillMakarov** [comment]
+1

**Comment by psychosk** [comment]
+1

**Comment by munix** [comment]
+1

**Comment by safakge** [comment]
+1

**Comment by Kuoyhout** [comment]
+1

**Comment by Dakor91** [comment]
+1

**Comment by mrmaffen** [comment]
just updated to 2.0.6
