### ISSUE TITLE
Create a documentation

### ISSUE THREAD

**Issue by QuentinRoy** [mrmaffen/vlc-android-sdk#34]
As new user of the sdk, it is almost impossible to understand how to use it even after several hours reading the source code (which should not be necessary).
Even some quick examples would help *a lot*.

**Comment by CRASH-Tech** [comment]
That is samples https://code.videolan.org/videolan/libvlc-android-samples

**Comment by mrmaffen** [comment]
Please contact the videolan team directly. I am only publishing LibVLC for Android on Maven Central.

https://trac.videolan.org/vlc
