### ISSUE TITLE
Can't play rtsp live stream

### ISSUE THREAD

**Issue by jordanSunco** [mrmaffen/vlc-android-sdk#41]
I've been working on an Android application that shows live streaming video via RTSP. Assuming I have a well-functioning RTSP server that passes h264 packets, and to view the stream we should connect to rtsp://192.168.42.1/live, old VLC player works fine, but this version cannot view the live stream.

Code like this:

            ArrayList<String> options = new ArrayList<String>();
            options.add("--aout=opensles");
            options.add("--audio-time-stretch"); // time stretching
            options.add("-vvv"); // verbosity
            //options.add
            libvlc = new LibVLC(options);
            holder.setKeepScreenOn(true);

            // Create media player
            mMediaPlayer = new MediaPlayer(libvlc);
            mMediaPlayer.setEventListener(mPlayerListener);

            // Set up video output
            final IVLCVout vout = mMediaPlayer.getVLCVout();
            vout.setVideoView(mSurface);
            vout.addCallback(this);
            vout.attachViews();
            //Media m = new Media(libvlc, media);
            Media mm = new Media(libvlc,Uri.parse(mVideoPath));
            mMediaPlayer.setMedia(mm);
            mMediaPlayer.play();

**Comment by mrmaffen** [comment]
Please contact the videolan team directly. I am only publishing LibVLC for Android on Maven Central.

https://trac.videolan.org/vlc
