### ISSUE TITLE
Initial Volume

### ISSUE THREAD

**Issue by thiagoalvescosta** [mrmaffen/vlc-android-sdk#43]
Hello,

Im trying to set initial volume with no sucess. If i use setVolume after play is not working, setVolume after some events like vout, playing is not working too and the option --volume=<value> is not working also.

Can you help-me ?

**Comment by mrmaffen** [comment]
Please contact the videolan team directly. I am only publishing LibVLC for Android on Maven Central.

https://trac.videolan.org/vlc
