### ISSUE TITLE
 long time to load 

### ISSUE THREAD

**Issue by iloveaman** [mrmaffen/vlc-android-sdk#50]
this is my vedio url:
http://video.kocla.com/Phonics.Kids.DVD.2_201609280833530524.avi?e=2137310110&token=kEUFey_36xJqHaOhr44fNd8eNUo4a9TLtMJSrqhu:LCcx_VvUkxLbYSPc7GcbRwvPVJY=

vlc takes a long time to load  when starting to play and seeking

**Comment by FabianTerhorst** [comment]
Open this issue please here: https://trac.videolan.org/vlc and close this issue.
