### ISSUE TITLE
apk gets 60MB in size with vlc lib

### ISSUE THREAD

**Issue by dinhka** [mrmaffen/vlc-android-sdk#53]
Hi,
I use compile 'de.mrmaffen:vlc-android-sdk:3.0.0' then my app has 30MB in size,
When i update to compile 'de.mrmaffen:vlc-android-sdk:1.9.8', the app get 60MB in size.
big size it not good to upload to Google Play.
Please help.

**Comment by filipproch** [comment]
@dinhka You should setup build configuration so that you have different APKs for each build type (armv7, x86_64, arm64, ...) and upload all of them to Play Store to your single app. This way you are packing all native libraries for all platforms with your apk which is useless.

**Comment by Saren-Arterius** [comment]
productFlavors {
        prod {
            ndk {
                abiFilter "armeabi-v7a"
            }
        }
    }

**Comment by shinayser** [comment]
Hey @Saren-Arterius,

is only "armeabi-v7a" enough for a production app ou should we add some more?

**Comment by Saren-Arterius** [comment]
@shinayser It depends. I am sure most (> 98%) android devices are compatible with "armeabi-v7a". The 64bit android devices could fallback using armeabi-v7a.

The problem is x86 devices.
