### ISSUE TITLE
RTMP playing problem - freeze after video stop streaming

### ISSUE THREAD

**Issue by GeniusAtamans** [mrmaffen/vlc-android-sdk#60]
When RTMP streaming is stop, I'm not get any event and exceptions, and app is freeze.

My init options:
ArrayList<String> options = new ArrayList<String>();
options.add("--file-caching=1500");
options.add("--avcodec-hw=vaapi");
options.add("--network-caching=1500");
options.add("--live-caching==1500");
options.add("--no-plugins-cache");
options.add("--avcodec-fast");
options.add("--avcodec-skiploopfilter=4");
options.add("--avcodec-dr");
options.add("-vvv");

**Comment by GeniusAtamans** [comment]
Is freeze even if internet is gone.

**Comment by lexius** [comment]
The same problem here (RTSP stream)
