### ISSUE TITLE
Does this libvlc compiled as release version?

### ISSUE THREAD

**Issue by dingyaguang117** [mrmaffen/vlc-android-sdk#9]
Realse version will remove assert. As the unknown networking status,  it's important in product environment.

**Comment by mrmaffen** [comment]
what? :D Sorry I'm afraid I don't understand what you mean...

**Comment by dingyaguang117** [comment]
Did you add release flag when compile VLC?

https://wiki.videolan.org/AndroidCompile#Compile

**Comment by mrmaffen** [comment]
no I didn't

**Comment by dingyaguang117** [comment]
I got it... thanks~

**Comment by LukePulverenti** [comment]
It is possible that can be corrected? thanks.

**Comment by adrien-aubel** [comment]
+1

**Comment by nthreads** [comment]
Hello everyone, this may be not the right place to ask. Can anyone here help me please finding documentation of "How to implement" above sdk in my own project? 

I'll be very thankful.

**Comment by mrmaffen** [comment]
The latest build (1.9.0) is a release build.
